### ISSUE TITLE
Tunnelblick recipe

### ISSUE THREAD

**Issue by opus-nbonenberger** [jelockwood/recipes#1]
@jelockwood Can you share your recipe for Tunnelblick mentioned here? 
https://groups.google.com/g/tunnelblick-discuss/c/UYeR7vv_rXM

I did not find it in your repository.

**Comment by jelockwood** [comment]
@opus-nbonenberger 
I had to go back and refresh my memory about this 😄 

The post you are referring to was my discussing a Munki post-install script I had previously used and I had found more recently that the file permissions were getting screwed up.

I am using an existing AutoPkg recipe to download Tunnelblick as below

[https://github.com/autopkg/homebysix-recipes/tree/master/Tunnelblick](https://github.com/autopkg/homebysix-recipes/tree/master/Tunnelblick)

I added in my munki override recipe my post-install script.

**Comment by opus-nbonenberger** [comment]
Yes, I am using this, too. With release of Tunnelblick 4.x, the postinstall script of this recipe somehow fails.

**Comment by jelockwood** [comment]
@opus-nbonenberger 
Here is a sanitised copy of my post-install script. I have not checked it recently as we have now moved away from using Tunnelblick. 

It is a fairly complex script as it is doing multiple things. It creates a file using the HereDoc function, it in my case is also restoring the entire Tunnelblick VPN config. This uses a combination again of the HereDoc function but also uses Base64 encoding and TAR so as to be able to restore entire folder structure as a Tunneblick config is actually a 'package' type of folder. OpenVPN only uses a single text file as a comparison. The script also tells Tunnelblick to trust the new setup - I am not convinced this is working fully probably due to Apple making things more and more complex with regards to security permissions.

See my older article about using a combination of TAR, Base64 and HereDoc in a script to restore items.

[https://jelockwood.blogspot.com/2018/06/using-cat-eof-in-shell-script-to.html](https://jelockwood.blogspot.com/2018/06/using-cat-eof-in-shell-script-to.html)

The section in the post-install script that does this has a comment line saying -

`# Export tunnelblick.tblk config`

I have removed (most) of my encoded file as it is specific to my site, it is marked as ending with the EOD line.

Below this EOD line you can see the considerable number of lines I added to 'fix' the file permissions as per the discussion you found.

[post-install.txt](https://github.com/jelockwood/recipes/files/14588383/post-install.txt)

**Comment by opus-nbonenberger** [comment]
@jelockwood thank you! i will check that out. Moving away from Tunnelblick sounds great. Do you use the official OpenVPN client now?

**Comment by jelockwood** [comment]
"thank you! i will check that out. Moving away from Tunnelblick sounds great. Do you use the official OpenVPN client now?"

God no. OpenVPN on a Mac is virtually impossible to automate installing configs for.

We now use Jamf Trust with its zero trust networking. It has so far proven to be a lot more reliable for always on VPN type connections. The goal was to ensure traffic was always protected even when users were at home or in public WiFi areas. We also use this on iOS devices as well.

**Comment by opus-nbonenberger** [comment]
Coincidentally we configured Jamf Trust ZTNA along with a Private Gateway to our Company network just yesterday but I am not pleased with the performance compared to SSL VPN directly to our Sophos Firewall.
